// auth0-guestblog-trustedtypes-react/src/App.js
import React, { useState } from "react";
import DOMPurify from "dompurify";

function App() {
  const [data, setData] = useState("");
  const [currentValue, setCurrentValue] = useState(`Hello!<img src="none" onerror="alert('This data has become code!')">`);

  let divRender2 = React.createRef();

  function handleChange(event) {
    setCurrentValue(event.target.value);
  }

  function renderData() {
    console.log(`Rendering data in the div: ${currentValue}`);
    setData(currentValue);

    divRender2.current.innerHTML = currentValue;
  }

  return (
    <>
      <h1>Trusted Types Demo</h1>
      <label htmlFor="taData" className="label">
        The (malicious) data to render
      </label>
      <textarea id="taData" className="element" value={currentValue} onChange={handleChange} />
      <button id="btnRender" className="element" onClick={renderData}>
        Render data
      </button>

      <label htmlFor="divRender1" className="label mt-4">
        The <code>div</code> with the rendered data using built-in React escaping
      </label>
      <div id="divRender1" className="element divRender">
        {data}
      </div>

      <label htmlFor="divRender2" className="label mt-4">
        The <code>div</code> with the rendered data being put into the DOM using the native <code>InnerHTML</code> through an escape hatch
      </label>
      <div id="divRender2" className="element divRender" ref={divRender2} />

      <label htmlFor="divRender3" className="label mt-4">
        The <code>div</code> with the rendered data being put into the DOM using <code>dangerouslySetInnerHTML</code> in combination with DOMPurify and Trusted Types
      </label>
      <div id="divRender3" className="element divRender" dangerouslySetInnerHTML={{__html: DOMPurify.sanitize(data, {RETURN_TRUSTED_TYPE: true})}} />
    </>
  );
}

export default App;

// auth0-guestblog-trustedtypes-angular/src/app/app.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],

})
export class AppComponent {
  value = `Hello!<img src="none" onerror="alert('This data has become code!')">`;
  renderedValue = "";
  unsafeRenderedValue;

  @ViewChild("divRender3") div : ElementRef;

  constructor(private sanitizer : DomSanitizer) {}

  renderData() {
    // Div 1
    this.renderedValue = this.value;

    // Div 2
    this.unsafeRenderedValue = this.sanitizer.bypassSecurityTrustHtml(this.value);

    // Div 3
    this.div.nativeElement.innerHTML = this.value;
  }
}

<h1>Trusted Types Demo</h1>

<label for="taData" class="label">The (malicious) data to render</label>
<textarea id="taData" class="element" [(ngModel)]="value"></textarea>
<button id="btnRender" class="element" (click)="renderData()">Render data</button>

<label for="divRender1" class="label mt-4">The <code>div</code> with the data passed through the Angular sanitizer</label>
<div id="divRender1" class="element divRender" [innerHTML]="renderedValue"></div>

<label for="divRender2" class="label mt-4">The <code>div</code> with the data passed through <code>bypassSecurityTrustHtml()</code></label>
<div id="divRender2" class="element divRender" [innerHTML]="unsafeRenderedValue"></div>

<label for="divRender3" class="label mt-4">The <code>div</code> with the data passed assigned directly to the native <code>innerHTML</code> sink</label>
<div #divRender3 id="divRender3" class="element divRender"></div>
